<?php

/**
 * @file
 * Contains bline_login.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bline_login_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bline_login module.
    case 'help.page.bline_login':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module to manage the bline login integration.') . '</p>';
      return $output;

    default:
  }
}
